### ISSUE TITLE
Any way to work on windows files ?

### ISSUE THREAD

**Issue by ucavalcante** [FachmannPremium/turbo-log#1]
im trying using with Windows and didtn work any way to do that ?
im using trough smb network.

**Comment by bwiercinski** [comment]
For this moment my extention only suports SFTP protocol, I am planning to expand this tool by listening to local files. Then I will consider also adding SMB Client. For this moment I found node client for this work. 
https://github.com/bchelli/node-smb2
I made this extention for my private usecase and just share it. Thanks for suggestion and using my work.

**Comment by ucavalcante** [comment]
tks for your response and your time good luck im will watching your progress.
